version: '3.6'

services:
  api:
    container_name: api
    restart: always
    environment:
      - NODE_ENV=development
      - MONGO_URL=fp_mongo
      - MONGO_PORT=27017
    build: .
    volumes:
      - .:/home/node/build
    depends_on:
      - fp_mongo
    links:
      - fp_mongo
    ports:
      - 3000:3000

  fp_mongo:
    image: mongo:latest
    container_name: fp_mongo
    restart: always
    ports:
      - "27017:27017"
